### ISSUE TITLE
Monitor connections to the backend servers not closing with PFS

### ISSUE THREAD

**Issue by 0x6d617474** [signal18/replication-manager#273]
We have recently started using RM to manage our simple master/slave cluster running MariaDB 10.3. 

```
[root@engr-dbprxy-201 ~]# replication-manager-cli version
Replication Manager 2.0.1 for MariaDB 10.x and MySQL 5.7 Series
Full Version:  2.0.1-18-gb4ffd27f
Build Time:  2018-11-25T09:58:56+0000
```

We have run into an issue where the RM process (run from another server) is opening connections to the backend servers to check state, but it is not closing the connections. The connection pool quickly fills up, and clients are unable to connect to the servers. Additionally, since RM itself is no longer able to connect, it assumes the backend servers have failed, and so attempts to initiate failover. 

Here are the configs for RM:  

<details><summary>config.toml</summary>
<p>

```toml

[Default]

include = "/etc/replication-manager/cluster.d"

failover-mode = "automatic"
failover-at-sync = true
failover-readonly = true
failover-pre-script = ""
failover-post-script = ""

autorejoin = true
autorejoin-backup-binlog = true
autorejoin-mysqldump = true
autorejoin-script = false
autorejoin-flashback-on-sync = true
autorejoin-slave-positional-hearbeat = true

switchover-at-equal-gtid = false    # This causes problems during switchover
switchover-at-sync = true
switchover-slave-wait-catch = true
switchover-wait-kill = 10000
switchover-wait-trx = 5
switchover-wait-write-query = 10

check-binlog-filters = true
check-replication-filters = true
check-replication-state = true

force-slave-readonly = true
force-sync-binlog = true
force-sync-innodb = true
force-slave-semisync = true
force-binlog-annotate-embedded = false
force-binlog-checksum = false
force-binlog-compress = true
force-binlog-row = true
force-binlog-slowqueries = false
force-slave-gtid-mode = true
force-slave-no-gtid-mode = false
force-slave-heartbeat = true
force-noslave-behind = true

log-file = "/var/log/replication-manager.log"
log-rotate = true
verbose = 1
log-level = 3
monitoring-ticker = 2
monitoring-scheduler = false # Automatically runs cleanup scripts. Don't

# Changing this requires the password to be used at the command-line
# Safe to leave defaults so long as the firewall denys access
# api-credential = "admin:repman"

graphite-embedded = true
graphite-metrics = true
graphite-carbon-api-port = "10002"

http-server = true
http-bind-address = "0.0.0.0"
http-port = "10001"
```
</p>
</details>

<details><summary>cluster.d/cluster01.toml</summary>
<p>

```toml

[cluster01]
title = "Main Cluster"
db-servers-hosts = "152.1.0.150,152.1.0.151,152.1.0.152"
db-servers-prefered-master = "152.1.0.150"
db-servers-ignored-hosts = "152.1.0.152"
db-servers-connect-timeout = 5
db-servers-read-timeout = 15
db-servers-credential = "sys_monitor:[REDACTED]"
db-servers-tls-ca-cert = ""
db-servers-tls-client-cert = ""
db-servers-tls-client-key = ""

replication-credential = "sys_replication:[REDACTED]"
replication-use-ssl = false
replication-master-slave = true

proxy-servers-read-on-master = "true"

proxysql = "true"
proxysql-servers = "152.1.0.155"
proxysql-port = "3306"
proxysql-admin-port = "6032"
proxysql-user = "prxyadmin"
proxysql-password = "[REDACTED]"
proxysql-bootstrap = false      # Servers are configured into ProxySQL via puppet
proxysql-copy-grants = true     # Copy users into proxysql when they are created at runtime
proxysql-writer-hostgroup = "0"
proxysql-reader-hostgroup = "1"

```
</p>
</details>

<details><summary>/var/log/replication-manager.log</summary>
<p>

```
2019/03/08 09:47:10 [cluster01] INFO  - New server monitored: 152.1.0.150
2019/03/08 09:47:10 [cluster01] INFO  - New server monitored: 152.1.0.151
2019/03/08 09:47:10 [cluster01] INFO  - New server monitored: 152.1.0.152
2019/03/08 09:47:10 [cluster01] INFO  - Failover in automatic mode
2019/03/08 09:47:10 [cluster01] INFO  - Loading 1 proxies
2019/03/08 09:47:10 [cluster01] INFO  - Loading ProxySQL...
2019/03/08 09:47:10 [cluster01] ERROR - No master found from replication
2019/03/08 09:47:10 [cluster01] INFO  - Set stateSlave from rejoin slave 152.1.0.151
2019/03/08 09:47:10 [cluster01] INFO  - Init Proxy Type: proxysql Host: 152.1.0.155 Port: 6032
2019/03/08 09:47:10 [cluster01] STATE - OPENED ERR00021 : All cluster db servers down
2019/03/08 09:47:10 [cluster01] STATE - OPENED WARN0058 : No GTID strict mode on slave 152.1.0.151
2019/03/08 09:47:10 [cluster01] STATE - OPENED WARN0070 : No GTID strict mode on master 152.1.0.150
2019/03/08 09:47:12 [cluster01] STATE - RESOLV ERR00021 : All cluster db servers down
```
</p>
</details>

<br/>

Here's a screenshot of the backend servers without replication-manager running:  

![image](https://user-images.githubusercontent.com/28965650/54042724-d1ab2700-4198-11e9-9ed1-9ea50e2b580c.png)

And here is the same but with replication-manager running for about 20-30 seconds: 
![image](https://user-images.githubusercontent.com/28965650/54042784-fbfce480-4198-11e9-8a36-1cba295be9b6.png)

As you can see, a lot of connections remain open. Interestingly, the master node (the top panel) correctly closes the connections; however, yesterday afternoon the situation was reversed, and only the master node was accumulating connections.  

Any thoughts on why this is happening, or how to fix it? I'm happy to provide more information if needed.
