### ISSUE TITLE
[QA] replication-manager lack of HA arbitrator documentation

### ISSUE THREAD

**Issue by leiless** [signal18/replication-manager#354]
Hi again @svaroqui, @tanji.

Our company wants to use arbitrator functionalities for replication-manager HA.

But I found that https://docs.signal18.io/ have little docs about how to config `[arbitrator]` in `config.toml`.

My current `config.toml`:

```toml
[Default]
title = "MariaDBClusterTest"
db-servers-hosts = "172.31.254.1:3306,172.31.254.2:3306,172.31.254.3:3306"
db-servers-prefered-master = "172.31.254.1:3306"
db-servers-credential = "root:123456"
replication-credential = "repl:123456"
failover-mode = "manual"
verbose = 1

[arbitrator]
# Don't know how to use
```

For a minimal arbitrator setup, does we only need to specify `arbitration-peer-hosts` in `[arbitrator]`?

SEE ALSO:
https://docs.signal18.io/configuration/clustering
https://github.com/signal18/replication-manager/issues/262

https://github.com/signal18/replication-manager/issues/209
https://github.com/signal18/replication-manager/issues/162

**Comment by leiless** [comment]
Hi, @tanji, would you mind help me out?

**Comment by svaroqui** [comment]
Hi Leilsess, sorry for late reply, arbitration is an enterprise feature  , that's why it's less documented . you can find sample config in https://github.com/signal18/replication-manager/tree/2.1/etc/local/features/arbitrator, and you need to download an -arb package  and install it in a third DC , you will also need to have a file setup https://github.com/signal18/replication-manager/blob/2.1/share/opensvc/account.yaml in /etc/replication-manager i think to start the arbitrator

**Comment by svaroqui** [comment]
db-servers-hosts and db-servers-credential are not needed when using driver sqllite

**Comment by leiless** [comment]
> Hi Leilsess, sorry for late reply, arbitration is an enterprise feature , that's why it's less documented .

Thanks for your reply, I'm currently evaluating signal18/replication-manager for production testing.
So if everything goes ok, we'll consider making an enterprise subscription.

---

I changed my config into:

```toml
[Default]
title = "MariaDBClusterTest"
db-servers-hosts = "172.31.254.1:3306,172.31.254.2:3306,172.31.254.3:3306"
db-servers-prefered-master = "172.31.254.1:3306"
db-servers-credential = "root:123456"
replication-credential = "repl:123456"
failover-mode = "manual"
verbose = 1

[arbitrator]
title = "arbitrator"
#db-servers-hosts = "172.31.254.1:3306"
#db-servers-credential = "root:123456"
arbitrator-driver = "sqlite"
```

And run replication-manager, but I got:
```
$ ./replication-manager-arb arbitrator --config config.toml
WARN[2021-06-28T18:31:41+08:00] No include directory in default section
WARN[2021-06-28T18:31:41+08:00] No monitoring-save-config variable in default section config change lost on restart
INFO[2021-06-28T18:31:41+08:00] Cluster discover from config: arbitrator
FATA[2021-06-28T18:31:41+08:00] Error opening arbitrator database: unable to open database file

```

**Comment by leiless** [comment]
FYI, I've fixed the `Error opening arbitrator database: unable to open database file` with

```
$ sudo touch /var/lib/replication-manager/arbitrator.db
$ sudo ./replication-manager-arb arbitrator --config config.toml
WARN[2021-06-28T19:12:49+08:00] No include directory in default section      
WARN[2021-06-28T19:12:49+08:00] No monitoring-save-config variable in default section config change lost on restart 
INFO[2021-06-28T19:12:49+08:00] Cluster discover from config: arbitrator     
INFO[2021-06-28T19:12:49+08:00] Arbitrator listening on 0.0.0.0:10001        

```

---

> you will also need to have a file setup https://github.com/signal18/replication-manager/blob/2.1/share/opensvc/account.yaml in /etc/replication-manager i think to start the arbitrator

Do I still need the `account.yaml` to get the arbitrator to work if the driver is `sqlite`?

**Comment by svaroqui** [comment]
Excellent , not it does need it looks like working now, what i found strange is that on my side i can delete that sqlite file  as many time as i wan't it is auto recreating it at startup , what os are you using ?

**Comment by leiless** [comment]
> what i found strange is that on my side i can delete that sqlite file as many time as i wan't it is auto recreating it at startup , what os are you using ?

Ubuntu 20.04 LTS amd64
Previously I run `replication-manager-arb` without root privilege, so the sqlite3 db file cannot be created.

But I still cannot get the difference between
`sudo ./replication-manager-osc --config config.toml monitor --http-server` and
`sudo ./replication-manager-arb arbitrator --config config.toml`

Since the first one is for mysql HA, and the second one is for repman itself HA.
Do I need to run them simultaneously?
If I ran both of 'em, I'll met `listen tcp 127.0.0.1:10001: bind: address already in use`.

---

After several minutes, the `arbitrator.db` still have no heartbeat at all...
```
$ sqlite3 arbitrator.db 'select count(*) from heartbeat'                   
0
```

**Comment by svaroqui** [comment]
Yes the arbitrator should be install on an other server , after that run 2 osc or pro release on 2 other servers , they will ping each other and when ping failed both will ask the arbitrator who is the winning one

**Comment by svaroqui** [comment]
leiless that arbitration code bring one single protection , when arbitration is on  the passive replication-manager is able to correctly setup the read only flag on a leader after a split brain so that if you get some proxysql  on the failed part it protect sending traffic to that failed master

**Comment by leiless** [comment]
Revised `config.toml`, but I still cannot get any heartbeat(sqlite select from heartbeat is empty):

```toml
[Default]
title = "MariaDBClusterTest"
db-servers-hosts = "172.31.254.1:3306,172.31.254.2:3306,172.31.254.3:3306"
db-servers-prefered-master = "172.31.254.1:3306"
db-servers-credential = "root:123456"
replication-credential = "repl:123456"
failover-mode = "manual"
verbose = true
log-heartbeat = true
arbitration-peer-hosts = "127.0.0.1:10000"
prov-orchestrator = "local"

[arbitrator]
title = "arbitrator"
arbitrator-driver = "sqlite"
arbitrator-bind-address = "0.0.0.0:10000"
```
