### ISSUE TITLE
Console rendering invalid characters on RHEL 8

### ISSUE THREAD

**Issue by ncstate-mafields** [signal18/replication-manager#549]
We recently started upgrading our servers to RHEL 8, and while everything seems to be functional, we are getting invalid characters rendered to the terminal when we use the CLI Console:

```
[root@dbmgr-dev ~]# replication-manager-cli console
%p1%dGQ������������������������������������������������������

 Replication Manager Client | Group: dev-cluster |  Mode: Manual �����������������������                                                                                                                                                                                                                                                                                                                                                          
Host   Port          Status   Failures   Using GTID         Current GTID           Slave GTID             Replication Health  Delay  RO���������������������                                            �����������������������>   
10.36.21.123   3306          Master          0           No 2-1451829552-10767,7-1451862526-13 2-1451843462-9911,7-1451862526-13                      Master OK      0 OFF�������������     
10.32.21.123   3306           Slave          0    Slave_Pos   2-1451843462-11622   2-1451829552-10767                     Running OK      0  ON
```

Updates to the terminal are not rendered correctly, and exiting the Console requires a `reset` command to restore the terminal to normal. 

I've tried both the v2.2.20 and v2.3.20 versions and both exhibit the same issue.

I've also verified the issue occurs in CentOS 8 Stream, to rule out any RHEL specific shenanigans.

**Comment by svaroqui** [comment]
Thanks for reporting we will try to improve on this when one get time in the team

**Comment by svaroqui** [comment]
Can you please just let us know the name of your cluster so that we can reproduce that bad printing ?

**Comment by ncstate-mafields** [comment]
Here's the `cluster.d/dev-cluster.toml`:

```toml
[dev-cluster]
title = "Dev Cluster"
db-servers-hosts = "10.36.21.123,10.32.21.123"
db-servers-prefered-master = "10.36.21.123"
db-servers-ignored-hosts = ""
db-servers-connect-timeout = 5
db-servers-read-timeout = 15
db-servers-credential = "[REDACTED]"
db-servers-tls-ca-cert = ""
db-servers-tls-client-cert = ""
db-servers-tls-client-key = ""

replication-credential = "[REDACTED]"
replication-use-ssl = false
replication-master-slave = true

proxy-servers-read-on-master = "true"
```
